### ISSUE TITLE
Add cohorts

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/buidlguidl-v3#75]
Get cohort data into Firebase + index events from contracts + expose API endpoint

ToDo
- [x] Create OG cohorts from script (#74)
- [x] Simple API to get DB cohort data (#74 )
- [x] Indexer script to get all contract events (mainnet & op) (#76)
- [x] Save events into database (#76)
- [x] Add cron to google cloud to call the indexer script (#76)
- [x] New event for withdraws (cohort.withdraw) to show in the /activity page (similar to stream.withdraw) (#76)
- [x] Create a BG account for cohorts members that are not in BG already
- [x] New admin page (as /admin/fund-builders) to show current balance of every cohort contract + latest withdraw / etc (extra: button to send ETH for each contract) (https://github.com/scaffold-eth/buidlguidl-v3/pull/79)
- [x] Stats for BG landing (totalWithdrawn global +  totalWithdrawn per cohort) /cohorts/stats (https://github.com/scaffold-eth/buidlguidl-v3/pull/80)
